-  
  prefix: App\Config\
  directory: Config
-  
  prefix: App\Controller\
  directory: Controller
- 
  prefix: App\Entity\
  directory: Entity
- 
  prefix: App\Repository\
  directory: Database  
  